#!/usr/bin/env bash

set -euo pipefail

usage() { echo "Usage: prep-for-debianish-build [pyxattr|xattr]"; }
misuse() { usage 1>&2; exit 2; }

xattr="${1:-pyxattr}"
minio="${_INSTALL_MINIO:-}"

case "$xattr" in
    pyxattr|xattr) ;;
    *) misuse ;;
esac

. /etc/os-release

# dosfstools: for vfat for the (root) tests
debs=(acl
      attr
      dosfstools
      duplicity
      curl
      gcc
      git
      graphviz
      kmod
      libacl1-dev
      libreadline-dev
      linux-libc-dev
      locales
      make
      man-db
      pandoc
      par2
      pkg-config
      python3-"$xattr"
      python3-dev
      python3-fuse
      python3-pytest
      python3-pytest-xdist
      python3-tornado
      python3-hypothesis
      python3-libnacl
      rdiff-backup
      rsync)

set -x

case "$VERSION_CODENAME" in
    bullseye|buster)
        debs+=(pylint3)
        ;;
    trixie)
        debs+=(pylint)
        ;;
    *)
        echo "unknown debian codename $VERSION_CODENAME"
        exit 2
        ;;
esac

export DEBIAN_FRONTEND=noninteractive
apt-get update
apt-get install -y "${debs[@]}"

if [ "$minio" = "y" ] ; then
    curl -o /usr/local/bin/minio https://dl.min.io/server/minio/release/linux-amd64/minio
    curl -o /usr/local/bin/mc https://dl.min.io/client/mc/release/linux-amd64/mc
    chmod +x /usr/local/bin/minio /usr/local/bin/mc
fi
