#!/usr/bin/env bash
. ./wvtest-bup.sh || exit $?

set -o pipefail

WVSTART 'all'

top="$(WVPASS pwd)" || exit $?
tmpdir="$(WVPASS wvmktempdir)" || exit $?

export BUP_DIR="$tmpdir/bup"

bup() { "$top/bup" "$@"; }

WVPASS mkdir "$tmpdir/foo"

bup save "$tmpdir/foo" -t &> /dev/null
rc=$?
WVPASSEQ "$rc" "15"

WVPASS cd "$top"
WVPASS rm -rf "$tmpdir"
